steps:
  # Build the React frontend
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--prefix', 'frontend']
    dir: 'frontend'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--prefix', 'frontend']
    dir: 'frontend'

  # Build the Flask backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/job-alert-backend', 'backend']

  # Push images to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/job-alert-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'job-alert-backend'  # Your Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/job-alert-backend'
      - '--region'
      - 'your-region'  # Replace with your desired region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # If you don't need auth yet

  # Deploy the React frontend (Option 1: Static site hosting)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['app', 'deploy', '--quiet', 'frontend/build/app.yaml']

  # Alternative: Deploy the React frontend (Option 2: Cloud Storage)
  #- name: 'gcr.io/cloud-builders/gsutil'
  #  args: ['cp', '-r', 'frontend/build', 'gs://your-bucket-name']
